# This is a config for E2B sandbox template.
# You can use template ID (qzv1h78rnvftdizmkfay) or template name (ripple_net_generic) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox.create("ripple_net_generic") # Sync sandbox
# sandbox = await AsyncSandbox.create("ripple_net_generic") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('ripple_net_generic')

#team_id = your team id here
start_cmd = "/compile_page.sh"
dockerfile = "e2b.Dockerfile"
template_name = "ripple_net_generic"
template_id = "qzv1h78rnvftdizmkfay"
